names = [
	'Amy Adams',
	'Adele',
	'Ben Affleck',
	'Christina Aguilera',
	'Akon',
	'Jessica Alba',
	'Alexander the Great',
	'Muhammad Ali',
	'Woody Allen',
	'Wes Anderson',
	'Andr\xc3\xa9 the Giant',
	'Jennifer Aniston',
	'Aristotle',
	'Kevin Bacon',
	'Christian Bale',
	'Elizabeth Banks',
	'Drew Barrymore',
	'Dave Batista',
	'Simone de Beauvoir',
	'David Beckham',
	'Ludwig van Beethoven',
	'Jordan Belfort',
	'Kristen Bell',
	'Mayim Bialik',
	'Justin Bieber',
	'Jessica Biel',
	'Cate Blanchett',
	'Lizzie Borden',
	'Lizzie Borden',
	'David Bowie',
	'Tom Brady',
	'Marlon Brando',
	'Chris Brown',
	'Kobe Bryant',
	'Warren Buffett',
	'Sandra Bullock',
	'Ted Bundy',
	'George W. Bush',
	'Julius Caesar',
	'Nicolas Cage',
	'Al Capone',
	'Truman Capote',
	'Mariah Carey',
	'Jim Carrey',
	'Pete Carroll',
	'Jimmy Carter',
	'Johnny Cash',
	'John Cena',
	'50 Cent',
	'Jackie Chan',
	'Charlie Chaplin',
	'Cher',
	'Priyanka Chopra',
	'Winston Churchill',
	'Winston Churchill',
	'Emilia Clarke',
	'Bill Clinton',
	'George Clooney',
	'Kurt Cobain',
	'Christopher Columbus',
	'Jennifer Connelly',
	'Sean Connery',
	'Harry Connick, Jr.',
	'Bradley Cooper',
	'Bryan Cranston',
	'Russell Crowe',
	'Tom Cruise',
	'Ice Cube',
	'Macaulay Culkin',
	'Benedict Cumberbatch',
	'Kaley Cuoco',
	'Miley Cyrus',
	'Leonardo Da Vinci',
	'Jeffrey Dahmer',
	'Matt Damon',
	'Charles Darwin',
	'Doris Day',
	'Robert De Niro',
	'Ellen DeGeneres',
	'Lana Del Rey',
	'Kat Dennings',
	'Johnny Depp',
	'Zooey Deschanel',
	'Cameron Diaz',
	'Leonardo DiCaprio',
	'Vin Diesel',
	'Peter Dinklage',
	'Walt Disney',
	'Snoop Dogg',
	'Michael Douglas',
	'Robert Downey, Jr.',
	'Dr. Dre',
	'Hilary Duff',
	'Lena Dunham',
	'Bob Dylan',
	'Amelia Earhart',
	'Clint Eastwood',
	'Thomas Edison',
	'Zac Efron',
	'Albert Einstein',
	'Dwight D. Eisenhower',
	'Chiwetel Ejiofor',
	'Idris Elba',
	'Eminem',
	'Jimmy Fallon',
	'Mia Farrow',
	'Michael Fassbender',
	'Roger Federer',
	'Harrison Ford',
	'Dian Fossey',
	'Megan Fox',
	'James Franco',
	'Anne Frank',
	'Benjamin Franklin',
	'Martin Freeman',
	'Morgan Freeman',
	'Sigmund Freud',
	'Galileo Galilei',
	'Mahatma Gandhi',
	'Judy Garland',
	'Bill Gates',
	'Peaches Geldof',
	'Mel Gibson',
	'Donald Glover',
	'Selena Gomez',
	'Joseph Gordon-Levitt',
	'Ryan Gosling',
	'Ellie Goulding',
	'Kelsey Grammer',
	'Ariana Grande',
	'Eva Green',
	'Sasha Grey',
	'Jonathan Groff',
	'Dave Grohl',
	'Che Guevara',
	'Jake Gyllenhaal',
	'Lucy Hale',
	'Tom Hanks',
	'Tonya Harding',
	'Tom Hardy',
	'Woody Harrelson',
	'Neil Patrick Harris',
	'George Harrison',
	'Kevin Hart',
	'Anne Hathaway',
	'Stephen Hawking',
	'Lena Headey',
	'Amber Heard',
	'Dorothy Height',
	'Ernest Hemingway',
	'Chris Hemsworth',
	'Liam Hemsworth',
	'Jimi Hendrix',
	'Audrey Hepburn',
	'Tom Hiddleston',
	'Jonah Hill',
	'Alfred Hitchcock',
	'Adolf Hitler',
	'Philip Seymour Hoffman',
	'E. T. A. Hoffmann',
	'Hulk Hogan',
	'Nicholas Hoult',
	'Howard Hughes',
	'Michael Hutchence',
	'Josh Hutcherson',
	'Sarah Hyland',
	'Enrique Iglesias',
	'Hugh Jackman',
	'Andrew Jackson',
	'Michael Jackson',
	'Mick Jagger',
	'LeBron James',
	'Theo James',
	'Jay-Z',
	'Thomas Jefferson',
	'Bruce Jenner',
	'Steve Jobs',
	'Scarlett Johansson',
	'Angelina Jolie',
	'Spike Jonze',
	'Michael Jordan',
	'Katrina Kaif',
	'Kim Kardashian',
	'Anna Kendrick',
	'John F. Kennedy',
	'Nancy Kerrigan',
	'Wiz Khalifa',
	'Aamir Khan',
	'Genghis Khan',
	'Salman Khan',
	'Salman Khan',
	'Shahrukh Khan',
	'Ban Ki-Moon',
	'Nicole Kidman',
	'Stephen King',
	'Keira Knightley',
	'Mila Kunis',
	'Ashton Kutcher',
	'Shia LaBeouf',
	'Osama bin Laden',
	'Lady Gaga',
	'Avril Lavigne',
	'Jennifer Lawrence',
	'Heath Ledger',
	'Bruce Lee',
	'John Legend',
	'Vladimir Lenin',
	'John Lennon',
	'Jay Leno',
	'Brock Lesnar',
	'Jared Leto',
	'Monica Lewinsky',
	'Abraham Lincoln',
	'Tara Lipinski',
	'Blake Lively',
	'Lindsay Lohan',
	'Jennifer Lopez',
	'Tina Louise',
	'Demi Lovato',
	'Martin Luther',
	'Seth MacFarlane',
	'Malcolm X',
	'Nelson Mandela',
	'Gucci Mane',
	'Michael E. Mann',
	'Peyton Manning',
	'Charles Manson',
	'Kate Mara',
	'Rooney Mara',
	'Marie Antoinette',
	'Bob Marley',
	'Bruno Mars',
	'Karl Marx',
	'Floyd Mayweather, Jr.',
	'Rachel McAdams',
	'Jenny McCarthy',
	'Paul McCartney',
	'Matthew McConaughey',
	'Jennette McCurdy',
	'Steve McQueen',
	'Idina Menzel',
	'Freddie Mercury',
	'Lionel Messi',
	'Bode Miller',
	'Nicki Minaj',
	'Kylie Minogue',
	'Hayao Miyazaki',
	'Michelle Monaghan',
	'Marilyn Monroe',
	'Julianne Moore',
	'Viggo Mortensen',
	'Wolfgang Amadeus Mozart',
	'Brittany Murphy',
	'Bill Murray',
	'Elon Musk',
	'Rafael Nadal',
	'Liam Neeson',
	'Isaac Newton',
	'Jack Nicholson',
	'Stevie Nicks',
	'Kim Novak',
	'Bill Nye',
	'Bill Nye',
	"Conan O'Brien",
	"Shaquille O'Neal",
	'Barack Obama',
	'Gary Oldman',
	'Elizabeth Olsen',
	'Al Pacino',
	'Ellen Page',
	'Gwyneth Paltrow',
	'Paris',
	'Rosa Parks',
	'Jim Parsons',
	'Paula Patton',
	'Aaron Paul',
	'Sarah Paulson',
	'Sean Penn',
	'Katy Perry',
	'Evan Peters',
	'Fred Phelps',
	'Joaquin Phoenix',
	'Pablo Picasso',
	'Brad Pitt',
	'Plies',
	'Edgar Allan Poe',
	'Amy Poehler',
	'Sidney Poitier',
	'Michael Pollan',
	'Natalie Portman',
	'Chris Pratt',
	'Elvis Presley',
	'CM Punk',
	'Vladimir Putin',
	'Harold Ramis',
	'Ronald Reagan',
	'Norman Reedus',
	'Keanu Reeves',
	'Ryan Reynolds',
	'Natasha Richardson',
	'Rihanna',
	'Emma Roberts',
	'Julia Roberts',
	'Jackie Robinson',
	'Dennis Rodman',
	'Michelle Rodriguez',
	'Cristiano Ronaldo',
	'Mickey Rooney',
	'Franklin D. Roosevelt',
	'Theodore Roosevelt',
	'Rick Ross',
	'Rick Ross',
	'Portia de Rossi',
	'J. K. Rowling',
	'Carl Sagan',
	'Andy Samberg',
	'Adam Sandler',
	'Eric Schlosser',
	'Michael Schumacher',
	'Arnold Schwarzenegger',
	'Martin Scorsese',
	'Pete Seeger',
	'Ayrton Senna',
	'William Shakespeare',
	'Shakira',
	'Tupac Shakur',
	'Ariel Sharon',
	'Charlie Sheen',
	'Frank Sinatra',
	'Skrillex',
	'Will Smith',
	'Cobie Smulders',
	'Kevin Spacey',
	'James Spader',
	'Britney Spears',
	'Steven Spielberg',
	'Bruce Springsteen',
	'Sylvester Stallone',
	'Ringo Starr',
	'Jason Statham',
	'Kristen Stewart',
	'Emma Stone',
	'Meryl Streep',
	'Taylor Swift',
	'Quentin Tarantino',
	'Channing Tatum',
	'Shirley Temple',
	'Sachin Tendulkar',
	'Mother Teresa',
	'Nikola Tesla',
	'Margaret Thatcher',
	'Charlize Theron',
	'Robin Thicke',
	'Emma Thompson',
	'Justin Timberlake',
	'John Travolta',
	'Triple H',
	'Harriet Tubman',
	'Tina Turner',
	'Yulia Tymoshenko',
	'Mike Tyson',
	'Neil deGrasse Tyson',
	'The Undertaker',
	'Kate Upton',
	'Vincent van Gogh',
	'Queen Victoria',
	'Donnie Wahlberg',
	'Mark Wahlberg',
	'Paul Walker',
	'Paul Walker',
	'Andy Warhol',
	'Denzel Washington',
	'George Washington',
	'Alice Waters',
	'Emma Watson',
	'Kanye West',
	'Shaun White',
	'Olivia Wilde',
	'Pharrell Williams',
	'Bruce Willis',
	'Oprah Winfrey',
	'Kate Winslet',
	'Stevie Wonder',
	'Shailene Woodley',
	'Viktor Yanukovych',
	'Paula Yates',
	'Susilo Bambang Yudhoyono',
	'Mark Zuckerberg'
];

tags = [
	'Junebug',
	'Rolling In The Deep',
	'Good Will Hunting',
	'Genie in a Bottle',
	'Trouble',
	'Dark Angel',
	'World conqueror',
	'Floated like butterfly, stung like bee',
	'Annie Hall',
	'Rushmore',
	'Professional wrestler with Giantism',
	'Rachel on Friends',
	'Politics',
	'Everybody cut Footloose',
	'The Dark Knight',
	'The Baxter',
	'E.T., The Wedding Singer',
	'Deacon Batista, WWE star',
	'The Second Sex',
	'Los Angeles Galaxy',
	'Prominent composer',
	'The Wolf of Wall Street',
	'Veronica Mars',
	'Blossom Russo on Blossom',
	'Baby',
	'The Rules of Attraction',
	'Galadriel in LOTR',
	'Born in Flames',
	'Presumed axe murderer',
	'Ziggy Stardust',
	'New England Patriots QB',
	'A Streetcar Named Desire',
	'R&B singer, Run It!',
	'Embattled Los Angeles Lakers star',
	'Billionaire in Omaha',
	'The Net',
	'Serial killer, blamed pornography',
	'43rd US President, 2001-09',
	'Roman Dictator 45 BC until 44 BC',
	'Leaving Las Vegas',
	'Scarface',
	'In Cold Blood',
	'Diva with eighteen #1 hits',
	'Rubber-faced fartsmith',
	'Seattle Seahawks coach',
	'39th US President, 1977-81',
	'The Man in Black',
	'WWE Champion',
	'Wanksta, P.I.M.P.',
	'Martial arts star, did his own stunts',
	'Silent film comedian',
	'Sonny and Cher',
	'Krrish',
	'Early 20th century American novelist',
	'WWII Prime Minister of England',
	'Daenerys Targaryen on Game of Thrones',
	'42nd US President, 1993-2001',
	'E.R.',
	'Lead singer of Nirvana',
	'Rediscovered the New World',
	'Betty Ross in The Hulk',
	'James Bond',
	'Golden voiced singer/actor',
	'Will Tippin on Alias',
	'Walter White on Breaking Bad',
	'A Beautiful Mind',
	'Flamboyant Scientologist',
	'N.W.A., Boyz N the Hood',
	'Home Alone',
	"BBC's Sherlock Holmes",
	'Bridget on 8 Simple Rules...',
	'Hannah Montana',
	'Mona Lisa, The Last Supper',
	'Homosexual serial killer cannibal',
	'Good Will Hunting',
	'Proposed theory of evolution via natural selection',
	'The Man Who Knew Too Much',
	'The Godfather: Part II',
	'Ellen',
	'Born to Die',
	"Nick and Norah's Infinite Playlist",
	'Captain Jack Sparrow',
	'New Girl',
	"There's Something About Mary",
	'Titanic',
	'Riddick from Pitch Black',
	'Tyrion Lannister on Game of Thrones',
	'Founder of Disney empire',
	"Sippin' on gin, juice",
	'Wall Street',
	'The Gingerbread Man',
	"Nuthin' but a 'G' Thang",
	'Manufactured pop star',
	'Tiny Furniture',
	"The Times They Are A-Changin'",
	'Misplaced aviatrix',
	'The Man With No Name',
	'Invented the light bulb',
	'High School Musical',
	'Theory of relativity',
	'34th US President, 1953-61',
	'Dirty Pretty Things',
	'The Wire',
	'The Real Slim Shady',
	'Saturday Night Live',
	"Rosemary's Baby",
	'Centurion',
	'Winner of 15 Grand Slam titles',
	'Han Solo in Star Wars',
	'Gorillas in the Mist',
	'Sydney Shanowski on Hope and Faith',
	'Freaks and Geeks',
	'The Diary of Anne Frank',
	'American founding father',
	'Tim on The Office',
	'Unforgiven',
	'Die Traumdeutung',
	'Copernican observational astronomer',
	'Proselytizer of nonviolence',
	'Dorothy in Wizard of Oz',
	'Co-Founder of Microsoft',
	'Daughter of Bob Geldof',
	'Mad Max',
	'Troy Barnes on Community',
	'Wizards of Waverly Place',
	'Third Rock From the Sun',
	'Murder by Numbers',
	'Lights',
	'Frasier',
	'Cat Valentine on Victorious',
	'The Dreamers',
	'The Girlfriend Experience',
	'Jesse St. James on Glee',
	'Nirvana, Foo Fighters',
	'Revolutionary icon',
	'Donnie Darko',
	'Aria Montgomery on Pretty Little Liars',
	'Forrest Gump',
	'Figure skater caused Olympic sized scandal',
	'Layer Cake',
	'Woody from Cheers',
	'Doogie Howser',
	'Beatle',
	'Kevin Hart: Laugh at My Pain',
	'The Princess Diaries',
	'Wheelchair-bound physicist',
	'The Remains of the Day',
	'And Soon The Darkness',
	'National Council of Negro Women',
	'The Old Man And The Sea',
	'The Mighty Thor',
	'The Hunger Games',
	'Purple Haze',
	'My Fair Lady',
	'Thor',
	'Superbad',
	'Master of Suspense',
	'Chancellor of Germany, 1933-45',
	'Character actor',
	'Das Fr\xc3\xa4ulein van Scuderi',
	'Hogan Knows Best',
	'About A Boy',
	'Insane billionaire',
	'INXS',
	'Bridge to Terabithia',
	'Haley Dunphy on Modern Family',
	'Balladeer',
	'X-Men',
	'7th US President, 1829-37',
	'King of Pop',
	'Lead singer of the Rolling Stones',
	'King James',
	'Jed Harper on Bedlam',
	'Can I Get A...',
	'3rd US President, 1801-09',
	'US Olympic track and field star',
	'Co-Founder of Apple Computer',
	'Ghost World, Lost in Translation',
	'Tomb Raider',
	'Being John Malkovich',
	"God's gift to basketball, clearly",
	'Namastey London',
	'Keeping Up With The Kardashians',
	'Up in the Air',
	'35th US President, 1961-63',
	'Figure skater hit by baton',
	'Black and Yellow',
	'Lagaan: Once Upon a Time in India',
	"World's most successful conqueror",
	'Top Bollywood megastar',
	'Founder, Khan Academy',
	'Hindi megastar',
	'UN Secretary General',
	'Moulin Rouge',
	'The Shining',
	'Bend It Like Beckham',
	"Jackie on That 70's Show",
	"Kelso on That '70s Show",
	'Wall Street: Money Never Sleeps',
	'Head of al Qaeda terrorist organization',
	'The Fame',
	'Manufactured pop star',
	"Winter's Bone",
	'Brokeback Mountain',
	'Enter the Dragon',
	'Get Lifted',
	'Revolutionary leader of Soviet Union',
	' Beatle',
	'The Tonight Show',
	'WWE Champion at age 25',
	'Harry in Requiem for a Dream',
	'Engaged in Presidential cigar play',
	'16th US President, 1861-65',
	'Olympic figure skater, now pro',
	'Gossip Girl',
	'Mean Girls',
	'Maid in Manhattan',
	"Ginger on Gilligan's Island",
	'Camp Rock',
	'Created Protestant movement',
	'Creator of Family Guy',
	'Nation of Islam',
	'Former President of South Africa',
	'Icy',
	'Climate change scientist',
	'Four-time MVP quarterback',
	'Helter Skelter',
	'Shooter',
	'The Girl with the Dragon Tattoo',
	'Cake proponent',
	'No Woman No Cry',
	'Doo-Wops & Hooligans',
	'Das Kapital, Communist Manifesto',
	'WBC Welterweight boxing champion',
	'The Notebook',
	'Early-nineties Playboy model, Singled Out',
	'Beatle',
	'Contact',
	'Sam on iCarly',
	'The Great Escape',
	'Rent',
	'Lead singer, Queen',
	'FC Barcelona',
	'Four-time world ski champion',
	'Pink Friday',
	'Red-blooded Australian pop singer',
	'Princess Mononoke',
	'Kiss Kiss Bang Bang',
	'Some Like It Hot',
	'Boogie Nights, Short Cuts',
	'Aragorn in Lord of the Rings',
	'Eine Kleine Nachtmusik',
	'Clueless',
	'Meatballs, SNL alumnus',
	'CEO of SpaceX and Tesla Motors',
	'Winner of four French Opens',
	'Rob Roy, Gangs of New York',
	'Father of the clockwork universe',
	'Chinatown',
	'Fleetwood Mac',
	'Vertigo doppelganger',
	'Bill Nye the Science Guy',
	'Bill Nye and Boomerang',
	'Briefly hosted The Tonight Show',
	'Shaq Attack',
	'44th President of the United States',
	'Sid Vicious in Sid and Nancy',
	'Martha Marcy May Marlene',
	'Michael Corleone in The Godfather',
	'Juno',
	'Shakespeare in Love',
	'The devil made him do it',
	"Wouldn't sit in the back of the bus",
	'Sheldon on The Big Bang Theory',
	'Deja Vu',
	'Jesse Pinkman on Breaking Bad',
	'Down with Love',
	'Fast Times at Ridgemont High',
	'I Kissed a Girl',
	'Tate Langdon on American Horror Story',
	'Convinced that God hates fags',
	'Gladiator',
	'Abstract painter and sculptor',
	"Ocean's Eleven",
	'The Real Testament',
	'The Raven',
	'Leslie Knope on Parks and Recreation',
	'In The Heat Of The Night',
	"The Omnivore's Dilemma",
	'Black Swan',
	'Everwood',
	'Rock and roll icon',
	'WWE and ECW wrestler',
	'President of Russia',
	'Egon Spengler in Ghostbusters',
	'40th US President, 1981-89',
	'Gossip',
	'Dude',
	'Van Wilder',
	"Widows' Peak",
	'Umbrella',
	'Addie Singer in Unfabulous',
	'Pretty Woman',
	'First negro in the major leagues',
	'Eccentric ex-pro basketball player',
	'Girlfight, Resident Evil',
	'Real Madrid',
	'Actor in Andy Hardy comedies, musicals',
	'US President during WWII',
	'26th US President, 1901-09',
	'Port of Miami',
	'Cult expert, deprogrammer',
	'Nelle Porter on Ally',
	'Author of Harry Potter series',
	'Popular astronomer, host of Cosmos',
	'SNL, The Lonely Island',
	'The Wedding Singer, SNL alumnus',
	'Fast Food Nation',
	'Formula 1 driver',
	'Governor of California, 2003-11',
	'Taxi Driver',
	'We Shall Overcome',
	'Three-time Formula 1 champion',
	'Romeo and Juliet, Hamlet, Macbeth',
	'Latin American legend',
	'All Eyez on Me',
	'Prime Minister of Israel, 2001-06',
	'The prodigal Sheen',
	"It's Frank's world, we just live in it",
	'Bangarang',
	'Fresh Prince of Bel Air',
	'How I Met Your Mother',
	'The Usual Suspects',
	'Sex, Lies, and Videotape',
	'Oops!... I Did it Again',
	'E.T.',
	'The Boss',
	'Rocky, Rambo',
	'Beatle',
	'Snatch',
	'Bella Swan in Twilight',
	'Superbad',
	'The Deer Hunter',
	'Country music sensation',
	'Pulp Fiction',
	'Model for Mountain Dew soda',
	'Rebecca of Sunnybrook Farm',
	'Top batsman in cricket',
	'Missionaries of Charity',
	'Invented alternating current',
	'UK Prime Minister, 1979-90',
	'Monster',
	'The Evolution of Robin Thicke',
	"Howard's End",
	'*NSYNC',
	'Saturday Night Fever',
	'Multiple WWE Champion',
	'Operated the Underground Railroad',
	"What's Love Got to Do With It",
	'Prime Minister of Ukraine, 2005',
	'Erratic heavyweight champion',
	'Astrophysicist',
	'Undefeated at WrestleMania',
	'Cover, 2012 Sports Illustrated Swimsuit Issue',
	'Troubled and brilliant painter',
	'Longest-reigning British monarch',
	'New Kids on the Block',
	'Formerly of the Funky Bunch',
	'CEO of The Sage Group plc',
	'2 Fast 2 Furious',
	'Pop Art movement',
	'Training Day',
	'1st US President, 1789-97',
	'Chez Panisse',
	'Hermione in Harry Potter films',
	'The College Dropout',
	'The Flying Tomato',
	'Skin',
	'The Neptunes',
	'Die Hard',
	'The Oprah Winfrey Show',
	'Titanic',
	'Signed, Sealed, and Delivered',
	'Amy Juergens on The Secret Life',
	'President of Ukraine',
	'Rock Stars in Their Underpants',
	'President of Indonesia',
	'Founder of Facebook'
];

rights = [
	'Bingo!',
	'Yes!',
	'Correct',
	'Nailed it',
	'Right',
	'You got it',
	'Check',
	'+1',
	'Affirmative'
];

wrongs = [
	'Nope',
	'Wrong',
	'Miss',
	'Missed it',
	'Incorrect',
	'Sorry'
];

cute_adjs = [
	'darling',
	'adorable',
	'huggable',
	'dainty',
	'fuzzy',
	'cutesy',
	'charming',
	'fluffy',
	'shiny',
	'cuddly',
	'sweet',
	'plush',
	'kissy',
	'snuggly'
];

cute_nouns = [
	'kitten',
	'marshmallow',
	'bubbles',
	'cinnamon',
	'pony',
	'gumdrop',
];

famous_adjs = [
	'acclaimed',
	'brilliant',
	'distinguished',
	'eminent',
	'excellent',
	'glorious',
	'grand',
	'great',
	'honored',
	'illustrious',
	'important',
	'influential',
	'leading',
	'memorable',
	'noted',
	'notorious',
	'outstanding',
	'powerful',
	'preeminent',
	'prominent',
	'recognized',
	'remarkable',
	'renowned',
	'splendid',
	'well-known',
	'applauded',
	'august',
	'celebrated',
	'conspicuous',
	'elevated',
	'exalted',
	'extraordinary',
	'foremost',
	'imposing',
	'lionized',
	'mighty',
	'much-publicized',
	'noble',
	'noteworthy',
	'peerless',
	'reputable',
	'signal',
	'talked-about'
];

famous_nouns = [
	'figure',
	'hero',
	'luminary',
	'personage',
	'personality',
	'someone',
	'star',
	'superstar',
	'ace',
	'bigwig',
	'cynosure',
	'heavyweight',
	'hotshot',
	'immortal',
	'lion',
	'magnate',
	'mahatma',
	'name',
	'notable',
	'somebody',
	'VIP',
	'worthy',
	'big-cheese',
	'big-shot',
	'celeb',
	'major-leaguer'
];
